name: Tests

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE'

jobs:
  tests:
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            script_name: 'make test'
          - os: macos-latest
            script_name: 'make test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Cache bashunit"
        uses: actions/cache@v4
        with:
          path: lib
          key: bashunit-${{ runner.os }}-${{ hashFiles('install-dependencies.sh') }}

      - name: "Install bashunit"
        run: bash install-dependencies.sh

      - name: Run Tests
        run: ${{ matrix.script_name }}
